/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GameType {
    id: GameTypeId;
    status: Variant_closed_open;
    name: string;
    createdAt: bigint;
    betTypes: Array<BetType>;
    marketId: MarketId;
}
export type BetId = bigint;
export type DepositRequestId = bigint;
export type WithdrawalRequestId = bigint;
export interface Bet {
    id: BetId;
    status: Variant_won_pending_lost;
    userId: Principal;
    createdAt: bigint;
    betType: BetType;
    marketId: MarketId;
    gameTypeId: GameTypeId;
    number: string;
    amount: bigint;
    payout?: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type MarketId = bigint;
export interface MarketResults {
    results: Array<Result>;
    marktetId: string;
}
export type GameTypeId = bigint;
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Market {
    id: MarketId;
    status: Variant_closed_open;
    closeTime: bigint;
    name: string;
    createdAt: bigint;
    openTime: bigint;
}
export interface Transaction {
    id: TransactionId;
    transactionType: {
        __kind__: "withdrawalRequest";
        withdrawalRequest: WithdrawalRequestId;
    } | {
        __kind__: "depositRequest";
        depositRequest: DepositRequestId;
    } | {
        __kind__: "winningPayout";
        winningPayout: BetId;
    } | {
        __kind__: "betPlacement";
        betPlacement: BetId;
    };
    userId: Principal;
    createdAt: bigint;
    amount: bigint;
}
export type TransactionId = bigint;
export interface Result {
    jodi: string;
    time: bigint;
    closeNumber: string;
    marketId: string;
    openNumber: string;
}
export interface TimeRange {
    timeStart: bigint;
    timeEnd: bigint;
}
export interface DepositRequest {
    id: DepositRequestId;
    utr: string;
    status: Variant_pending_approved_rejected;
    userId: Principal;
    createdAt: bigint;
    reviewedAt?: bigint;
    reviewer?: Principal;
    amount: bigint;
}
export interface WithdrawalRequest {
    id: WithdrawalRequestId;
    status: Variant_pending_approved_rejected;
    userId: Principal;
    createdAt: bigint;
    reviewedAt?: bigint;
    upiId: string;
    reviewer?: Principal;
    amount: bigint;
}
export interface UserProfile {
    username: string;
    balance: bigint;
    totalWinnings: bigint;
    totalWithdrawals: bigint;
    totalDeposits: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum BetType {
    doublePanna = "doublePanna",
    jodi = "jodi",
    singlePanna = "singlePanna",
    single = "single",
    triplePanna = "triplePanna"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_closed_open {
    closed = "closed",
    open = "open"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum Variant_won_pending_lost {
    won = "won",
    pending = "pending",
    lost = "lost"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addResult(market: string, openNumber: string, closeNumber: string, jodi: string): Promise<void>;
    approveDepositRequest(_requestId: DepositRequestId): Promise<boolean>;
    approveWithdrawalRequest(_requestId: WithdrawalRequestId): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createGameType(_name: string, _marketId: MarketId, _betTypes: Array<BetType>): Promise<GameTypeId>;
    createMarket(_name: string, _openTime: bigint, _closeTime: bigint): Promise<MarketId>;
    declareGameResult(_marketId: MarketId, _openNumber: string, _closeNumber: string, _jodi: string, _singlePanna: Array<bigint>, _doublePanna: Array<bigint>, _triplePanna: Array<bigint>): Promise<boolean>;
    getAllGameTypes(): Promise<Array<GameType>>;
    getAllMarkets(): Promise<Array<Market>>;
    getBetHistory(user: Principal): Promise<Array<Bet>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGameType(gameTypeId: GameTypeId): Promise<GameType | null>;
    getPendingDepositRequests(): Promise<Array<DepositRequest>>;
    getPendingWithdrawalRequests(): Promise<Array<WithdrawalRequest>>;
    getPlatformStats(): Promise<{
        activeUsers: bigint;
        totalBets: bigint;
        totalWithdrawals: bigint;
        totalPayout: bigint;
        totalDeposits: bigint;
    }>;
    getResults(markets: Array<string>, _range: TimeRange | null): Promise<Array<MarketResults>>;
    getTransactionHistory(user: Principal): Promise<Array<Transaction>>;
    getUserBets(user: Principal): Promise<Array<Bet>>;
    getUserProfile(arg0: Principal): Promise<UserProfile | null>;
    getUserTransactions(user: Principal): Promise<Array<Transaction>>;
    isCallerAdmin(): Promise<boolean>;
    placeBet(_gameTypeId: GameTypeId, _betType: BetType, _number: string, _amount: bigint): Promise<BetId>;
    registerUser(username: string): Promise<void>;
    rejectDepositRequest(_requestId: DepositRequestId): Promise<boolean>;
    rejectWithdrawalRequest(_requestId: WithdrawalRequestId): Promise<boolean>;
    saveCallerUserProfile(arg0: UserProfile): Promise<void>;
    submitDepositRequest(_amount: bigint, _utr: string): Promise<DepositRequestId>;
    submitWithdrawalRequest(_amount: bigint, _upiId: string): Promise<WithdrawalRequestId>;
    updateMarketStatus(_marketId: MarketId, _status: Variant_closed_open): Promise<boolean>;
}
import type { Bet as _Bet, BetId as _BetId, BetType as _BetType, DepositRequest as _DepositRequest, DepositRequestId as _DepositRequestId, GameType as _GameType, GameTypeId as _GameTypeId, Market as _Market, MarketId as _MarketId, TimeRange as _TimeRange, Transaction as _Transaction, TransactionId as _TransactionId, UserProfile as _UserProfile, UserRole as _UserRole, WithdrawalRequest as _WithdrawalRequest, WithdrawalRequestId as _WithdrawalRequestId, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addResult(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addResult(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResult(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async approveDepositRequest(arg0: DepositRequestId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveDepositRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveDepositRequest(arg0);
            return result;
        }
    }
    async approveWithdrawalRequest(arg0: WithdrawalRequestId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWithdrawalRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWithdrawalRequest(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createGameType(arg0: string, arg1: MarketId, arg2: Array<BetType>): Promise<GameTypeId> {
        if (this.processError) {
            try {
                const result = await this.actor.createGameType(arg0, arg1, to_candid_vec_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGameType(arg0, arg1, to_candid_vec_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createMarket(arg0: string, arg1: bigint, arg2: bigint): Promise<MarketId> {
        if (this.processError) {
            try {
                const result = await this.actor.createMarket(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMarket(arg0, arg1, arg2);
            return result;
        }
    }
    async declareGameResult(arg0: MarketId, arg1: string, arg2: string, arg3: string, arg4: Array<bigint>, arg5: Array<bigint>, arg6: Array<bigint>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.declareGameResult(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.declareGameResult(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async getAllGameTypes(): Promise<Array<GameType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGameTypes();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGameTypes();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMarkets(): Promise<Array<Market>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMarkets();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMarkets();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBetHistory(arg0: Principal): Promise<Array<Bet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBetHistory(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBetHistory(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGameType(arg0: GameTypeId): Promise<GameType | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameType(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameType(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingDepositRequests(): Promise<Array<DepositRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingDepositRequests();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingDepositRequests();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingWithdrawalRequests(): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingWithdrawalRequests();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingWithdrawalRequests();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlatformStats(): Promise<{
        activeUsers: bigint;
        totalBets: bigint;
        totalWithdrawals: bigint;
        totalPayout: bigint;
        totalDeposits: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformStats();
            return result;
        }
    }
    async getResults(arg0: Array<string>, arg1: TimeRange | null): Promise<Array<MarketResults>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResults(arg0, to_candid_opt_n40(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResults(arg0, to_candid_opt_n40(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getTransactionHistory(arg0: Principal): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionHistory(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionHistory(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserBets(arg0: Principal): Promise<Array<Bet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBets(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBets(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTransactions(arg0: Principal): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTransactions(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTransactions(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async placeBet(arg0: GameTypeId, arg1: BetType, arg2: string, arg3: bigint): Promise<BetId> {
        if (this.processError) {
            try {
                const result = await this.actor.placeBet(arg0, to_candid_BetType_n11(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeBet(arg0, to_candid_BetType_n11(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async registerUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0);
            return result;
        }
    }
    async rejectDepositRequest(arg0: DepositRequestId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectDepositRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectDepositRequest(arg0);
            return result;
        }
    }
    async rejectWithdrawalRequest(arg0: WithdrawalRequestId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectWithdrawalRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectWithdrawalRequest(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitDepositRequest(arg0: bigint, arg1: string): Promise<DepositRequestId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDepositRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDepositRequest(arg0, arg1);
            return result;
        }
    }
    async submitWithdrawalRequest(arg0: bigint, arg1: string): Promise<WithdrawalRequestId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitWithdrawalRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitWithdrawalRequest(arg0, arg1);
            return result;
        }
    }
    async updateMarketStatus(arg0: MarketId, arg1: Variant_closed_open): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMarketStatus(arg0, to_candid_variant_n45(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMarketStatus(arg0, to_candid_variant_n45(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BetType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BetType): BetType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Bet_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bet): Bet {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_DepositRequest_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DepositRequest): DepositRequest {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_GameType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameType): GameType {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Market_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Market): Market {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalRequest_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalRequest): WithdrawalRequest {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GameType]): GameType | null {
    return value.length === 0 ? null : from_candid_GameType_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _GameTypeId;
    status: {
        closed: null;
    } | {
        open: null;
    };
    name: string;
    createdAt: bigint;
    betTypes: Array<_BetType>;
    marketId: _MarketId;
}): {
    id: GameTypeId;
    status: Variant_closed_open;
    name: string;
    createdAt: bigint;
    betTypes: Array<BetType>;
    marketId: MarketId;
} {
    return {
        id: value.id,
        status: from_candid_variant_n16(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        betTypes: from_candid_vec_n17(_uploadFile, _downloadFile, value.betTypes),
        marketId: value.marketId
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MarketId;
    status: {
        closed: null;
    } | {
        open: null;
    };
    closeTime: bigint;
    name: string;
    createdAt: bigint;
    openTime: bigint;
}): {
    id: MarketId;
    status: Variant_closed_open;
    closeTime: bigint;
    name: string;
    createdAt: bigint;
    openTime: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n16(_uploadFile, _downloadFile, value.status),
        closeTime: value.closeTime,
        name: value.name,
        createdAt: value.createdAt,
        openTime: value.openTime
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BetId;
    status: {
        won: null;
    } | {
        pending: null;
    } | {
        lost: null;
    };
    userId: Principal;
    createdAt: bigint;
    betType: _BetType;
    marketId: _MarketId;
    gameTypeId: _GameTypeId;
    number: string;
    amount: bigint;
    payout: [] | [bigint];
}): {
    id: BetId;
    status: Variant_won_pending_lost;
    userId: Principal;
    createdAt: bigint;
    betType: BetType;
    marketId: MarketId;
    gameTypeId: GameTypeId;
    number: string;
    amount: bigint;
    payout?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n26(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        createdAt: value.createdAt,
        betType: from_candid_BetType_n18(_uploadFile, _downloadFile, value.betType),
        marketId: value.marketId,
        gameTypeId: value.gameTypeId,
        number: value.number,
        amount: value.amount,
        payout: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.payout))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DepositRequestId;
    utr: string;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    userId: Principal;
    createdAt: bigint;
    reviewedAt: [] | [bigint];
    reviewer: [] | [Principal];
    amount: bigint;
}): {
    id: DepositRequestId;
    utr: string;
    status: Variant_pending_approved_rejected;
    userId: Principal;
    createdAt: bigint;
    reviewedAt?: bigint;
    reviewer?: Principal;
    amount: bigint;
} {
    return {
        id: value.id,
        utr: value.utr,
        status: from_candid_variant_n34(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        createdAt: value.createdAt,
        reviewedAt: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.reviewedAt)),
        reviewer: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.reviewer)),
        amount: value.amount
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _WithdrawalRequestId;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    userId: Principal;
    createdAt: bigint;
    reviewedAt: [] | [bigint];
    upiId: string;
    reviewer: [] | [Principal];
    amount: bigint;
}): {
    id: WithdrawalRequestId;
    status: Variant_pending_approved_rejected;
    userId: Principal;
    createdAt: bigint;
    reviewedAt?: bigint;
    upiId: string;
    reviewer?: Principal;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n34(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        createdAt: value.createdAt,
        reviewedAt: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.reviewedAt)),
        upiId: value.upiId,
        reviewer: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.reviewer)),
        amount: value.amount
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TransactionId;
    transactionType: {
        withdrawalRequest: _WithdrawalRequestId;
    } | {
        depositRequest: _DepositRequestId;
    } | {
        winningPayout: _BetId;
    } | {
        betPlacement: _BetId;
    };
    userId: Principal;
    createdAt: bigint;
    amount: bigint;
}): {
    id: TransactionId;
    transactionType: {
        __kind__: "withdrawalRequest";
        withdrawalRequest: WithdrawalRequestId;
    } | {
        __kind__: "depositRequest";
        depositRequest: DepositRequestId;
    } | {
        __kind__: "winningPayout";
        winningPayout: BetId;
    } | {
        __kind__: "betPlacement";
        betPlacement: BetId;
    };
    userId: Principal;
    createdAt: bigint;
    amount: bigint;
} {
    return {
        id: value.id,
        transactionType: from_candid_variant_n44(_uploadFile, _downloadFile, value.transactionType),
        userId: value.userId,
        createdAt: value.createdAt,
        amount: value.amount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
}): Variant_closed_open {
    return "closed" in value ? Variant_closed_open.closed : "open" in value ? Variant_closed_open.open : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    doublePanna: null;
} | {
    jodi: null;
} | {
    singlePanna: null;
} | {
    single: null;
} | {
    triplePanna: null;
}): BetType {
    return "doublePanna" in value ? BetType.doublePanna : "jodi" in value ? BetType.jodi : "singlePanna" in value ? BetType.singlePanna : "single" in value ? BetType.single : "triplePanna" in value ? BetType.triplePanna : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    won: null;
} | {
    pending: null;
} | {
    lost: null;
}): Variant_won_pending_lost {
    return "won" in value ? Variant_won_pending_lost.won : "pending" in value ? Variant_won_pending_lost.pending : "lost" in value ? Variant_won_pending_lost.lost : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_approved_rejected {
    return "pending" in value ? Variant_pending_approved_rejected.pending : "approved" in value ? Variant_pending_approved_rejected.approved : "rejected" in value ? Variant_pending_approved_rejected.rejected : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    withdrawalRequest: _WithdrawalRequestId;
} | {
    depositRequest: _DepositRequestId;
} | {
    winningPayout: _BetId;
} | {
    betPlacement: _BetId;
}): {
    __kind__: "withdrawalRequest";
    withdrawalRequest: WithdrawalRequestId;
} | {
    __kind__: "depositRequest";
    depositRequest: DepositRequestId;
} | {
    __kind__: "winningPayout";
    winningPayout: BetId;
} | {
    __kind__: "betPlacement";
    betPlacement: BetId;
} {
    return "withdrawalRequest" in value ? {
        __kind__: "withdrawalRequest",
        withdrawalRequest: value.withdrawalRequest
    } : "depositRequest" in value ? {
        __kind__: "depositRequest",
        depositRequest: value.depositRequest
    } : "winningPayout" in value ? {
        __kind__: "winningPayout",
        winningPayout: value.winningPayout
    } : "betPlacement" in value ? {
        __kind__: "betPlacement",
        betPlacement: value.betPlacement
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GameType>): Array<GameType> {
    return value.map((x)=>from_candid_GameType_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BetType>): Array<BetType> {
    return value.map((x)=>from_candid_BetType_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Market>): Array<Market> {
    return value.map((x)=>from_candid_Market_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bet>): Array<Bet> {
    return value.map((x)=>from_candid_Bet_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DepositRequest>): Array<DepositRequest> {
    return value.map((x)=>from_candid_DepositRequest_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawalRequest>): Array<WithdrawalRequest> {
    return value.map((x)=>from_candid_WithdrawalRequest_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n42(_uploadFile, _downloadFile, x));
}
function to_candid_BetType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BetType): _BetType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimeRange | null): [] | [_TimeRange] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BetType): {
    doublePanna: null;
} | {
    jodi: null;
} | {
    singlePanna: null;
} | {
    single: null;
} | {
    triplePanna: null;
} {
    return value == BetType.doublePanna ? {
        doublePanna: null
    } : value == BetType.jodi ? {
        jodi: null
    } : value == BetType.singlePanna ? {
        singlePanna: null
    } : value == BetType.single ? {
        single: null
    } : value == BetType.triplePanna ? {
        triplePanna: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_closed_open): {
    closed: null;
} | {
    open: null;
} {
    return value == Variant_closed_open.closed ? {
        closed: null
    } : value == Variant_closed_open.open ? {
        open: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<BetType>): Array<_BetType> {
    return value.map((x)=>to_candid_BetType_n11(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
