/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bet {
  'id' : BetId,
  'status' : { 'won' : null } |
    { 'pending' : null } |
    { 'lost' : null },
  'userId' : Principal,
  'createdAt' : bigint,
  'betType' : BetType,
  'marketId' : MarketId,
  'gameTypeId' : GameTypeId,
  'number' : string,
  'amount' : bigint,
  'payout' : [] | [bigint],
}
export type BetId = bigint;
export type BetType = { 'doublePanna' : null } |
  { 'jodi' : null } |
  { 'singlePanna' : null } |
  { 'single' : null } |
  { 'triplePanna' : null };
export interface DepositRequest {
  'id' : DepositRequestId,
  'utr' : string,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'userId' : Principal,
  'createdAt' : bigint,
  'reviewedAt' : [] | [bigint],
  'reviewer' : [] | [Principal],
  'amount' : bigint,
}
export type DepositRequestId = bigint;
export interface GameType {
  'id' : GameTypeId,
  'status' : { 'closed' : null } |
    { 'open' : null },
  'name' : string,
  'createdAt' : bigint,
  'betTypes' : Array<BetType>,
  'marketId' : MarketId,
}
export type GameTypeId = bigint;
export interface Market {
  'id' : MarketId,
  'status' : { 'closed' : null } |
    { 'open' : null },
  'closeTime' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'openTime' : bigint,
}
export type MarketId = bigint;
export interface Transaction {
  'id' : TransactionId,
  'transactionType' : { 'withdrawalRequest' : WithdrawalRequestId } |
    { 'depositRequest' : DepositRequestId } |
    { 'winningPayout' : BetId } |
    { 'betPlacement' : BetId },
  'userId' : Principal,
  'createdAt' : bigint,
  'amount' : bigint,
}
export type TransactionId = bigint;
export interface UserProfile {
  'username' : string,
  'balance' : bigint,
  'totalWinnings' : bigint,
  'totalWithdrawals' : bigint,
  'totalDeposits' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WithdrawalRequest {
  'id' : WithdrawalRequestId,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'userId' : Principal,
  'createdAt' : bigint,
  'reviewedAt' : [] | [bigint],
  'upiId' : string,
  'reviewer' : [] | [Principal],
  'amount' : bigint,
}
export type WithdrawalRequestId = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveDepositRequest' : ActorMethod<[DepositRequestId], boolean>,
  'approveWithdrawalRequest' : ActorMethod<[WithdrawalRequestId], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGameType' : ActorMethod<
    [string, MarketId, Array<BetType>],
    GameTypeId
  >,
  'createMarket' : ActorMethod<[string, bigint, bigint], MarketId>,
  'declareGameResult' : ActorMethod<
    [
      MarketId,
      string,
      string,
      string,
      Array<bigint>,
      Array<bigint>,
      Array<bigint>,
    ],
    boolean
  >,
  'getAllGameTypes' : ActorMethod<[], Array<GameType>>,
  'getAllMarkets' : ActorMethod<[], Array<Market>>,
  'getBetHistory' : ActorMethod<[Principal], Array<Bet>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGameType' : ActorMethod<[GameTypeId], [] | [GameType]>,
  'getPendingDepositRequests' : ActorMethod<[], Array<DepositRequest>>,
  'getPendingWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getPlatformStats' : ActorMethod<
    [],
    {
      'activeUsers' : bigint,
      'totalBets' : bigint,
      'totalWithdrawals' : bigint,
      'totalPayout' : bigint,
      'totalDeposits' : bigint,
    }
  >,
  'getTransactionHistory' : ActorMethod<[Principal], Array<Transaction>>,
  'getUserBets' : ActorMethod<[Principal], Array<Bet>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTransactions' : ActorMethod<[Principal], Array<Transaction>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeBet' : ActorMethod<[GameTypeId, BetType, string, bigint], BetId>,
  'registerUser' : ActorMethod<[string], undefined>,
  'rejectDepositRequest' : ActorMethod<[DepositRequestId], boolean>,
  'rejectWithdrawalRequest' : ActorMethod<[WithdrawalRequestId], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitDepositRequest' : ActorMethod<[bigint, string], DepositRequestId>,
  'submitWithdrawalRequest' : ActorMethod<
    [bigint, string],
    WithdrawalRequestId
  >,
  'updateMarketStatus' : ActorMethod<
    [MarketId, { 'closed' : null } | { 'open' : null }],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];