/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const DepositRequestId = IDL.Nat;
export const WithdrawalRequestId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MarketId = IDL.Nat;
export const BetType = IDL.Variant({
  'doublePanna' : IDL.Null,
  'jodi' : IDL.Null,
  'singlePanna' : IDL.Null,
  'single' : IDL.Null,
  'triplePanna' : IDL.Null,
});
export const GameTypeId = IDL.Nat;
export const GameType = IDL.Record({
  'id' : GameTypeId,
  'status' : IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null }),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'betTypes' : IDL.Vec(BetType),
  'marketId' : MarketId,
});
export const Market = IDL.Record({
  'id' : MarketId,
  'status' : IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null }),
  'closeTime' : IDL.Int,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'openTime' : IDL.Int,
});
export const BetId = IDL.Nat;
export const Bet = IDL.Record({
  'id' : BetId,
  'status' : IDL.Variant({
    'won' : IDL.Null,
    'pending' : IDL.Null,
    'lost' : IDL.Null,
  }),
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'betType' : BetType,
  'marketId' : MarketId,
  'gameTypeId' : GameTypeId,
  'number' : IDL.Text,
  'amount' : IDL.Nat,
  'payout' : IDL.Opt(IDL.Nat),
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'balance' : IDL.Nat,
  'totalWinnings' : IDL.Nat,
  'totalWithdrawals' : IDL.Nat,
  'totalDeposits' : IDL.Nat,
});
export const DepositRequest = IDL.Record({
  'id' : DepositRequestId,
  'utr' : IDL.Text,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'reviewedAt' : IDL.Opt(IDL.Int),
  'reviewer' : IDL.Opt(IDL.Principal),
  'amount' : IDL.Nat,
});
export const WithdrawalRequest = IDL.Record({
  'id' : WithdrawalRequestId,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'reviewedAt' : IDL.Opt(IDL.Int),
  'upiId' : IDL.Text,
  'reviewer' : IDL.Opt(IDL.Principal),
  'amount' : IDL.Nat,
});
export const TimeRange = IDL.Record({
  'timeStart' : IDL.Int,
  'timeEnd' : IDL.Int,
});
export const Result = IDL.Record({
  'jodi' : IDL.Text,
  'time' : IDL.Int,
  'closeNumber' : IDL.Text,
  'marketId' : IDL.Text,
  'openNumber' : IDL.Text,
});
export const MarketResults = IDL.Record({
  'results' : IDL.Vec(Result),
  'marktetId' : IDL.Text,
});
export const TransactionId = IDL.Nat;
export const Transaction = IDL.Record({
  'id' : TransactionId,
  'transactionType' : IDL.Variant({
    'withdrawalRequest' : WithdrawalRequestId,
    'depositRequest' : DepositRequestId,
    'winningPayout' : BetId,
    'betPlacement' : BetId,
  }),
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addResult' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'approveDepositRequest' : IDL.Func([DepositRequestId], [IDL.Bool], []),
  'approveWithdrawalRequest' : IDL.Func([WithdrawalRequestId], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGameType' : IDL.Func(
      [IDL.Text, MarketId, IDL.Vec(BetType)],
      [GameTypeId],
      [],
    ),
  'createMarket' : IDL.Func([IDL.Text, IDL.Int, IDL.Int], [MarketId], []),
  'declareGameResult' : IDL.Func(
      [
        MarketId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Nat),
        IDL.Vec(IDL.Nat),
        IDL.Vec(IDL.Nat),
      ],
      [IDL.Bool],
      [],
    ),
  'getAllGameTypes' : IDL.Func([], [IDL.Vec(GameType)], ['query']),
  'getAllMarkets' : IDL.Func([], [IDL.Vec(Market)], ['query']),
  'getBetHistory' : IDL.Func([IDL.Principal], [IDL.Vec(Bet)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGameType' : IDL.Func([GameTypeId], [IDL.Opt(GameType)], ['query']),
  'getPendingDepositRequests' : IDL.Func(
      [],
      [IDL.Vec(DepositRequest)],
      ['query'],
    ),
  'getPendingWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getPlatformStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'activeUsers' : IDL.Nat,
          'totalBets' : IDL.Nat,
          'totalWithdrawals' : IDL.Nat,
          'totalPayout' : IDL.Nat,
          'totalDeposits' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getResults' : IDL.Func(
      [IDL.Vec(IDL.Text), IDL.Opt(TimeRange)],
      [IDL.Vec(MarketResults)],
      ['query'],
    ),
  'getTransactionHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserBets' : IDL.Func([IDL.Principal], [IDL.Vec(Bet)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTransactions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeBet' : IDL.Func([GameTypeId, BetType, IDL.Text, IDL.Nat], [BetId], []),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'rejectDepositRequest' : IDL.Func([DepositRequestId], [IDL.Bool], []),
  'rejectWithdrawalRequest' : IDL.Func([WithdrawalRequestId], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitDepositRequest' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [DepositRequestId],
      [],
    ),
  'submitWithdrawalRequest' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [WithdrawalRequestId],
      [],
    ),
  'updateMarketStatus' : IDL.Func(
      [MarketId, IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null })],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const DepositRequestId = IDL.Nat;
  const WithdrawalRequestId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MarketId = IDL.Nat;
  const BetType = IDL.Variant({
    'doublePanna' : IDL.Null,
    'jodi' : IDL.Null,
    'singlePanna' : IDL.Null,
    'single' : IDL.Null,
    'triplePanna' : IDL.Null,
  });
  const GameTypeId = IDL.Nat;
  const GameType = IDL.Record({
    'id' : GameTypeId,
    'status' : IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null }),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'betTypes' : IDL.Vec(BetType),
    'marketId' : MarketId,
  });
  const Market = IDL.Record({
    'id' : MarketId,
    'status' : IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null }),
    'closeTime' : IDL.Int,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'openTime' : IDL.Int,
  });
  const BetId = IDL.Nat;
  const Bet = IDL.Record({
    'id' : BetId,
    'status' : IDL.Variant({
      'won' : IDL.Null,
      'pending' : IDL.Null,
      'lost' : IDL.Null,
    }),
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'betType' : BetType,
    'marketId' : MarketId,
    'gameTypeId' : GameTypeId,
    'number' : IDL.Text,
    'amount' : IDL.Nat,
    'payout' : IDL.Opt(IDL.Nat),
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'balance' : IDL.Nat,
    'totalWinnings' : IDL.Nat,
    'totalWithdrawals' : IDL.Nat,
    'totalDeposits' : IDL.Nat,
  });
  const DepositRequest = IDL.Record({
    'id' : DepositRequestId,
    'utr' : IDL.Text,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'reviewedAt' : IDL.Opt(IDL.Int),
    'reviewer' : IDL.Opt(IDL.Principal),
    'amount' : IDL.Nat,
  });
  const WithdrawalRequest = IDL.Record({
    'id' : WithdrawalRequestId,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'reviewedAt' : IDL.Opt(IDL.Int),
    'upiId' : IDL.Text,
    'reviewer' : IDL.Opt(IDL.Principal),
    'amount' : IDL.Nat,
  });
  const TimeRange = IDL.Record({ 'timeStart' : IDL.Int, 'timeEnd' : IDL.Int });
  const Result = IDL.Record({
    'jodi' : IDL.Text,
    'time' : IDL.Int,
    'closeNumber' : IDL.Text,
    'marketId' : IDL.Text,
    'openNumber' : IDL.Text,
  });
  const MarketResults = IDL.Record({
    'results' : IDL.Vec(Result),
    'marktetId' : IDL.Text,
  });
  const TransactionId = IDL.Nat;
  const Transaction = IDL.Record({
    'id' : TransactionId,
    'transactionType' : IDL.Variant({
      'withdrawalRequest' : WithdrawalRequestId,
      'depositRequest' : DepositRequestId,
      'winningPayout' : BetId,
      'betPlacement' : BetId,
    }),
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addResult' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'approveDepositRequest' : IDL.Func([DepositRequestId], [IDL.Bool], []),
    'approveWithdrawalRequest' : IDL.Func(
        [WithdrawalRequestId],
        [IDL.Bool],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGameType' : IDL.Func(
        [IDL.Text, MarketId, IDL.Vec(BetType)],
        [GameTypeId],
        [],
      ),
    'createMarket' : IDL.Func([IDL.Text, IDL.Int, IDL.Int], [MarketId], []),
    'declareGameResult' : IDL.Func(
        [
          MarketId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Nat),
          IDL.Vec(IDL.Nat),
          IDL.Vec(IDL.Nat),
        ],
        [IDL.Bool],
        [],
      ),
    'getAllGameTypes' : IDL.Func([], [IDL.Vec(GameType)], ['query']),
    'getAllMarkets' : IDL.Func([], [IDL.Vec(Market)], ['query']),
    'getBetHistory' : IDL.Func([IDL.Principal], [IDL.Vec(Bet)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGameType' : IDL.Func([GameTypeId], [IDL.Opt(GameType)], ['query']),
    'getPendingDepositRequests' : IDL.Func(
        [],
        [IDL.Vec(DepositRequest)],
        ['query'],
      ),
    'getPendingWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getPlatformStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'activeUsers' : IDL.Nat,
            'totalBets' : IDL.Nat,
            'totalWithdrawals' : IDL.Nat,
            'totalPayout' : IDL.Nat,
            'totalDeposits' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getResults' : IDL.Func(
        [IDL.Vec(IDL.Text), IDL.Opt(TimeRange)],
        [IDL.Vec(MarketResults)],
        ['query'],
      ),
    'getTransactionHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserBets' : IDL.Func([IDL.Principal], [IDL.Vec(Bet)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTransactions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeBet' : IDL.Func(
        [GameTypeId, BetType, IDL.Text, IDL.Nat],
        [BetId],
        [],
      ),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'rejectDepositRequest' : IDL.Func([DepositRequestId], [IDL.Bool], []),
    'rejectWithdrawalRequest' : IDL.Func([WithdrawalRequestId], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitDepositRequest' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [DepositRequestId],
        [],
      ),
    'submitWithdrawalRequest' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [WithdrawalRequestId],
        [],
      ),
    'updateMarketStatus' : IDL.Func(
        [MarketId, IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null })],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };